### ISSUE TITLE
This script already patched.

### ISSUE THREAD

**Issue by zYxDevs** [xcscxr/ouo-bypass#6]
No more working. ouo has changed their sites.

**Comment by X-Gorn** [comment]
They've fucked up their website with cloudflare.

**Comment by awaleedpk** [comment]
not working.

**Comment by xgorn** [comment]
> not working.

already fixed, update with the latest code

**Comment by zYxDevs** [comment]
> > not working.
> 
> already fixed, update with the latest code

already patched again by ouo. try it

**Comment by xgorn** [comment]
> > > not working.
> > 
> > 
> > already fixed, update with the latest code
> 
> already patched again by ouo. try it

nope. it's still working for me. i've tried it.

**Comment by xcscxr** [comment]
@zYxDevs @awaleedpk
provide detailed feedback and attach any error messages for better understanding and specificity, avoiding vague descriptions like "patched" or "not working." :)

**Comment by zYxDevs** [comment]
> @zYxDevs @awaleedpk provide detailed feedback and attach any error messages for better understanding and specificity, avoiding vague descriptions like "patched" or "not working." :)

its working fine after i try another links. looks like only get error on few ouo links.

**Comment by awaleedpk** [comment]
> @zYxDevs @awaleedpk provide detailed feedback and attach any error messages for better understanding and specificity, avoiding vague descriptions like "patched" or "not working." :)

Sorry, i tried on Google Colab, its working. Thanks for the Tool, Keep it up.
