### ISSUE TITLE
How to run script?

### ISSUE THREAD

**Issue by TheModMaster8** [xcscxr/ouo-bypass#7]
As someone who doesn't use python very much, it is a really confusing on how one is to install/run? this script. can a simple readme.txt doc be made for those, like myself. containing a super brief explanation on how to operate this. for example does it use Tampermonkey? is it always running in the background? is it a commandline script? do you need to use IDLE to run it? things like this. would help the less informed? Thanks anyways!

**Comment by xcscxr** [comment]
Edit the URL in code, install python on your system, run `python ouo-bypass.py`
